### PR TITLE
feat: add function for the suggestions rendering

### PR DESCRIPTION
**Pull request by denistakeda**
for #DIF-135

---
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/15)

### CODE REVIEW

**Comment by kennethlynne** [comment]
> Closes #DIF-135 partially
you cannot write "Closes #DIF-135 partially" in the description. As long as the jira plugin sees `Closes #DIF-135` it will close the issue

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15#-:-Kde7uaY2YzzPUidK_yQ:b3vt9e0)*

**Comment by kennethlynne** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/GiftedChat.js, line 485 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15#-Kde7zw-csxKEU3D4hJT:-Kde7zw-csxKEU3D4hJU:b-pi9d9n) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/9601d9264e85c78125da0281e1be7806cf1961b1/src/GiftedChat.js#L485)):*
> ```JavaScript
>   },
>   suggestions: {
>     //flex: 1,
> ```

remove this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15)*

**Comment by denistakeda** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/GiftedChat.js, line 485 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15#-Kde7zw-csxKEU3D4hJT:-Kde88yFppDS8aSlwyvH:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/9601d9264e85c78125da0281e1be7806cf1961b1/src/GiftedChat.js#L485)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15)*

**Comment by AlmaasAre** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15#-:-Kde8EcOPvj1KBgSXsFT:bg7igkv)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/15#-:-Kde8Prs1IdPIokflDGH:bnfp4nl)*

**Pull request merged**
