### PR TITLE
feature: dynamically grow text input

### PR DESCRIPTION
**Pull request by ncthis**
---
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/7)

### CODE REVIEW

**Comment by sondremare** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[GiftedMessenger.js, line 568 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PXc8gS6eXwyC7SlV:-KT8PXc8gS6eXwyC7SlW:b8jpig) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L568)):*
> ```JavaScript
> 
>   onTextInputHeightChange = (newHeight, oldHeight, changedBy) => {
>     this.listViewMaxHeight = this.props.maxHeight - Math.max(newHeight, 44);
> ```

This 44 should be moved to a constant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[GiftedMessenger.js, line 92 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PPVq8L7lRCGCfhZg:-KT8PPVq8L7lRCGCfhZh:b-i2g8ho) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L92)):*
> ```JavaScript
>       textInput: {
>         alignSelf: 'flex-end',
>         // height: 30, // won't work because we autogrow
> ```

remove it then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-:-KT8PjEkxn3YlSe8mKFF:bnfp4nl)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[GiftedMessenger.js, line 580 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PhrsUaYC8m-H95YG:-KT8PhrsUaYC8m-H95YH:b-pzb9kg) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L580)):*
> ```JavaScript
>   renderTextInput() {
>     const containerStyle = Object.assign({}, this.styles.textInputContainer, {
>       height: this.state.textHeight && this.state.textHeight + 6 > this.styles.textInputContainer.height ? this.state.textHeight + 6 : this.styles.textInputContainer.height,
> ```

this number 6 should also be a constant

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[GiftedMessenger.js, line 580 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PhrsUaYC8m-H95YG:-KT8Poeb-KJPAXX9v5tA:b-m7tkbv) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L580)):*
<details><summary><i>Previously, sondremare wrote…</i></summary>
> this number 6 should also be a constant
</details>
so we can know what it is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7)*

**Comment by AlmaasAre** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-:-KT8Q7gweMkjLURMGUIf:bnfp4nl)*

**Comment by ncthis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[GiftedMessenger.js, line 92 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PPVq8L7lRCGCfhZg:-KT8S1hNhC8JrTDXNRdf:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L92)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary>
> remove it then?
</details>
Done.

---

*[GiftedMessenger.js, line 568 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PXc8gS6eXwyC7SlV:-KT8S26rjpJfH0tU4yrz:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L568)):*
<details><summary><i>Previously, sondremare wrote…</i></summary>
> This 44 should be moved to a constant
</details>
Done.

---

*[GiftedMessenger.js, line 580 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-KT8PhrsUaYC8m-H95YG:-KT8S2lh_0SSZTkzQiQ9:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/cb8c56ab589016dab9e3de7ce383c601c105a2b4/GiftedMessenger.js#L580)):*
<details><summary><i>Previously, sondremare wrote…</i></summary>
> so we can know what it is
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7)*

**Comment by sondremare** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7#-:-KT8SBC8MXL6F3krsx8_:bnfp4nl)*

**Comment by sondremare** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/7)*

**Pull request merged**
