### PR TITLE
chore: update from source repository 

### PR DESCRIPTION
**Pull request by kennethlynne**
Get updates from FaridSafi/react-native-gifted-chat to be closer to their implementation to allow us to more easily get in future fixes and features, and stuff like flat list implementation from a fork

This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/32)

### CODE REVIEW

**Comment by sondremare** [comment]
Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 32 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAoy7S0ELqBqKGnLAs:-KwAoy7T8F9ctXM89JzT:b-vuqirc) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/4351453712ecc70a0ab0b6d2417955e5b0078c69/package.json#L32)):*
> ```JSON
>   "scripts": {
>     "lint": "eslint . --ext .js,.jsx",
>     "test": "npm run lint"
> ```

why is this removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAp3cucH6mCZ5RI305:-KwAp3cucH6mCZ5RI306:b-k86itc) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/8b687f75d4b5b8f8bb49aa3474f39cd085ebb02a/package.json#L48)):*
> ```JSON
>     "prop-types": "15.5.10",
>     "react-native-communications": "2.2.1",
>     "react-native-invertible-scroll-view": "1.0.0",
> ```

this will most likely break Android 7 versions due to transform scale: -1 problem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/GiftedChat.js, line 263 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAqTYkhS-VJIn4lnzW:-KwAqTYkhS-VJIn4lnzX:bpgtd7w) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/8b687f75d4b5b8f8bb49aa3474f39cd085ebb02a/src/GiftedChat.js#L263)):*
> ```JavaScript
>     this.setKeyboardHeight(e.endCoordinates ? e.endCoordinates.height : e.end.height);
>     this.setBottomOffset(this.props.bottomOffset);
>     const newMessagesContainerHeight = this.getMessagesContainerHeightWithKeyboard();
> ```

All of these changes to height needs to be tested thoroughly.
- When we hide input.
- When keyboard is active
- etc.. (couldnt think of anyone else atm)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-:-KwFc4yKtnw3FW9DnSO4:bnfp4nl)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package.json, line 32 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAoy7S0ELqBqKGnLAs:-KwJkVOf8YjLMO2RCnuZ:b-zhbf8t) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/4351453712ecc70a0ab0b6d2417955e5b0078c69/package.json#L32)):*
<details><summary><i>Previously, sondremare wrote…</i></summary><blockquote>

why is this removed?
</blockquote></details>

not in line with what is on their master, and it breaks the build

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[package.json, line 48 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAp3cucH6mCZ5RI305:-KwJkccl-qy-pzLK_qPP:b-navnvk) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/8b687f75d4b5b8f8bb49aa3474f39cd085ebb02a/package.json#L48)):*
<details><summary><i>Previously, sondremare wrote…</i></summary><blockquote>

this will most likely break Android 7 versions due to transform scale: -1 problem
</blockquote></details>

Comments in our fork said it was fixed in RN 0.48 >

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/GiftedChat.js, line 263 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-KwAqTYkhS-VJIn4lnzW:-KwJkm7T1Xu5clzUiyTR:bebrt1w) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/8b687f75d4b5b8f8bb49aa3474f39cd085ebb02a/src/GiftedChat.js#L263)):*
<details><summary><i>Previously, sondremare wrote…</i></summary><blockquote>

All of these changes to height needs to be tested thoroughly.
- When we hide input.
- When keyboard is active
- etc.. (couldnt think of anyone else atm)
</blockquote></details>

Will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by denistakeda** [comment]
:lgtm:

---

Review status: 42 of 45 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-:-Kx8EGpqXLhEUXMjXzr5:bnfp4nl)*

**Comment by kennethlynne** [comment]
Reviewed 42 of 45 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/GiftedChat.js, line 568 at r2](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-Kx8FKitljiCN9SwFYiP:-Kx8FKitljiCN9SwFYiQ:bnyonbh) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/4351453712ecc70a0ab0b6d2417955e5b0078c69/src/GiftedChat.js#L568)):*
> ```JavaScript
>   renderSend: PropTypes.func,
>   renderTime: PropTypes.func,
>   renderSuggestions: PropTypes.func,
> ```

I do not see renderSuggestions on the right hand side now, missing? Does suggestions still work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Comment by kennethlynne** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-:-Kx8FxmYzrNkipf1Z5YA:bg7igkv)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/GiftedChat.js, line 568 at r2](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32#-Kx8FKitljiCN9SwFYiP:-Kx8L-uWJp-4WBn_jkeT:b-b1g5af) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/4351453712ecc70a0ab0b6d2417955e5b0078c69/src/GiftedChat.js#L568)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

I do not see renderSuggestions on the right hand side now, missing? Does suggestions still work?
</blockquote></details>

Suggetstions still work, but will readd this proptype

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/32)*

**Pull request merged**
