### PR TITLE
feat(send): the restriction mechanism for send message

### PR DESCRIPTION
**Pull request by denistakeda**
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-gifted-messenger/37)

### CODE REVIEW

**Comment by AlmaasAre** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37#-:-KzxI5hAHvj1NlGxDD3N:bnfp4nl)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37#-:-KzxLwEqG_VgdeC3PaS1:bnfp4nl)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/GiftedChat.js, line 354 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37#-KzxMHlNKMAja2QVSxVD:-KzxMHlNKMAja2QVSxVE:b-5ipxt5) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/6c887c5143d68b9802c2809cc5a19dd2b0e5b662/src/GiftedChat.js#L354)):*
> ```JavaScript
>     this.props.onSend(messages);
> 
>     if (this.props.shouldResetInputToolbar) {
> ```

I'd prefer a prop "shouldScrollToBottom" instead. As reseting the toolbar is not really connected to scrolling to bottom

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37)*

**Comment by denistakeda** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/GiftedChat.js, line 354 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37#-KzxMHlNKMAja2QVSxVD:-KzxN1l1DcI_RONjShws:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-gifted-messenger/blob/6c887c5143d68b9802c2809cc5a19dd2b0e5b662/src/GiftedChat.js#L354)):*
<details><summary><i>Previously, sondremare wrote…</i></summary><blockquote>

I'd prefer a prop "shouldScrollToBottom" instead. As reseting the toolbar is not really connected to scrolling to bottom
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37)*

**Comment by sondremare** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-gifted-messenger/37#-:-KzxNkR_Y8AiHludIit6:bnfp4nl)*

**Pull request merged**
